name = "aim-coach-discord-bot"
main = "src/index.ts"
compatibility_date = "2023-10-30"
node_compat = true

[env.development]
name = "aim-coach-discord-bot-dev"

[env.staging]
name = "aim-coach-discord-bot-staging"

[env.production]
name = "aim-coach-discord-bot-prod"

# Environment variables (set via wrangler secret)
# Required for discord-hono:
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
#
# Required for AimCoach services:
# ANALYTICS_ENGINE_URL
# CONVERSATION_ENGINE_URL
# INTERNAL_API_TOKEN

# Durable Objects binding
[[durable_objects.bindings]]
name = "USER_SESSION"
class_name = "UserSession"

# KV binding
[[kv_namespaces]]
binding = "BOT_CONFIG"
id = "placeholder"
preview_id = "placeholder"