name = "aim-coach-discord-bot"
main = "src/index.ts"
compatibility_date = "2023-10-30"
node_compat = true

[env.development]
name = "aim-coach-discord-bot-dev"

[env.staging]
name = "aim-coach-discord-bot-staging"

[env.production]
name = "aim-coach-discord-bot-prod"

# Environment variables (set via wrangler secret)
# Discord Bot Configuration:
# wrangler secret put DISCORD_TOKEN
# wrangler secret put DISCORD_PUBLIC_KEY
# wrangler secret put DISCORD_APPLICATION_ID
#
# External Service URLs:
# wrangler secret put ANALYTICS_ENGINE_URL
# wrangler secret put CONVERSATION_ENGINE_URL
#
# Internal API Authentication:
# wrangler secret put INTERNAL_API_TOKEN
#
# Development URLs (examples):
# ANALYTICS_ENGINE_URL=https://analytics.aim-coach-dev.workers.dev
# CONVERSATION_ENGINE_URL=https://conversation.aim-coach-dev.workers.dev

# Durable Objects binding
[[durable_objects.bindings]]
name = "USER_SESSION"
class_name = "UserSession"

# KV binding
[[kv_namespaces]]
binding = "BOT_CONFIG"
id = "placeholder"
preview_id = "placeholder"